name: lifebeat
description: An application that helps you achieve goals and organize your schedule.
publish_to: 'none'
version: 0.5.0

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  sqflite: ^2.3.0
  sqflite_common_ffi: ^2.3.0+3
  path: ^1.8.3
  flutter_datetime_picker_plus: ^2.1.0
  window_manager: ^0.3.7
  shared_preferences: ^2.2.2
  file_picker: ^6.1.1
  permission_handler: ^11.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"
  min_sdk_android: 21
  windows:
    generate: true
    icon_size: 48
    image_path: "assets/images/icon.png"
  macos:
    generate: true
    image_path: "assets/images/icon.png"

flutter:
  uses-material-design: true

  fonts:
    - family: Manrope
      fonts:
        - asset: fonts/manrope/Manrope-Bold.ttf
        - asset: fonts/manrope/Manrope-ExtraBold.ttf
        - asset: fonts/manrope/Manrope-ExtraLight.ttf
        - asset: fonts/manrope/Manrope-Light.ttf
        - asset: fonts/manrope/Manrope-Medium.ttf
        - asset: fonts/manrope/Manrope-Regular.ttf
        - asset: fonts/manrope/Manrope-SemiBold.ttf